### ISSUE TITLE
automations.yaml error

### ISSUE THREAD

**Issue by loewal** [9V1KG/hass-openwebrx#1]
Hi,
perhaps a little too early, because things are still in alpha:
![Scherm­afbeelding 2024-07-03 om 10 01 36](https://github.com/9V1KG/hass-openwebrx/assets/7289719/ece87ae1-ce2b-4489-959c-ebce84f20758)

**Comment by 9V1KG** [comment]
Yes, I'm still working on it. Changed automations to blueprints. Feedback welcomed.
